apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-k
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-app-k
  template:
    metadata:
      labels:
        app: sample-app-k
    spec:
      containers:
      - command:
        - /app/sample-app
        image: gitopsbook/sample-app:REPLACEME   #A
        name: sample-app-k
        ports:
        - containerPort: 8080